export const defaults:Record<string,string>={
'identity.name':'World Prayer and Missions Network','identity.tagline':'Revealing Christ. Equipping His Family. Discipling the Nations.','identity.short':'World Prayer and Missions Network is a Christ-centered mission network committed to revealing Christ, equipping His family, and discipling the nations through prayer, teaching, discipleship, leadership formation, and mission.',
'home.heroHeading':'World Prayer and\nMissions Network','home.heroIntro':'Rooted in the finished work of Christ. Growing together in shared life. Participating in God’s mission, wherever we are.','home.heroImage':'/images/shared-life.jpg','home.heroAlt':'Two adults sharing in the life of the church','home.pathsHeading':'Where would you like to begin?','home.pathsIntro':'Whether you are exploring Christianity, looking for a church family, or wanting to understand our teaching more clearly, there is a simple place to begin.',
'home.identityHeading':'One mission network,\nvisible local communities','home.identityBody':'WPMN is the wider mission network. It gives theological direction, prayer focus, leadership training, and mission vision.\n\nEpignosis Christian Family is one visible community expression of WPMN. ECF gathers believers, students, families, and seekers into Sunday worship, house churches, discipleship, shared life, and service.',
'home.beliefsHeading':'Christ at the center of\nScripture, life, and mission','home.beliefsBody':'We believe the Scriptures find their center and fulfillment in Christ. The gospel is the announcement of what God has accomplished in His Son.\n\nThrough His death and resurrection, Christ has dealt with sin and brought believers into new life in Him. Our life together flows from union with Christ and the work of the Spirit.',
'home.gatherHeading':'There is room for you here.','home.gatherBody':'You do not need to understand everything before you come. You can visit, listen, ask questions, and take your next step at a healthy pace.',
'home.houseHeading':'Discipleship happens\nin shared life','home.houseBody':'In smaller gatherings, believers pray, share life, ask questions, care for one another, and learn to participate in service. We return again and again to belonging, wisdom, service, and mission as Christ forms us.','home.houseImage':'/images/shared-life.jpg','home.houseAlt':'Adults listening and spending time together at church',
'home.mediaHeading':'Keep learning. Keep returning to Christ.','home.mediaBody':'Explore Christ-centered teaching for ordinary life, shared faith, and faithful service. Begin with an article, or browse the teaching archive.',
'home.collegeHeading':'Equipping leaders\nfor faithful service','home.collegeBody':'Epignosis Leadership College equips believers for Christ-centered leadership, teaching, discipleship, and service in the body of Christ. Training currently operates in Shilan, Benguet and Baguio City.',
'home.giveHeading':'Participate in the mission','home.giveBody':'Your generosity helps support discipleship, leadership training, campus communities, outreach, and the ongoing work of revealing Christ and equipping His family.',
'home.connectHeading':'Take your next step','home.connectBody':'Whether you want to visit, request prayer, join discipleship, inquire about leadership training, or explore partnership, we would be glad to hear from you.',
'about.heading':'A spiritual family,\nsharing the mission of Christ.','about.intro':'World Prayer and Missions Network exists to serve the mission of Christ by forming people and communities around the gospel.','about.mission':'We exist to love God wholeheartedly and His people faithfully, equipping families and individuals to embody and proclaim the Christ-centered gospel, walking together in obedience to the Great Commission.','about.vision':'To become a radiant Christ-centered family, reflecting His love to the world and raising up disciples from every nation until all find their home in Him.','about.ecf':'Epignosis Christian Family is a Christ-centered spiritual family within the wider mission of WPMN. Our campus communities gather believers, students, families, and seekers around the gospel of Christ, the teaching of Scripture, prayer, fellowship, and practical service.',
'beliefs.heading':'We begin with Christ.\nAnd we keep returning to Him.','beliefs.intro':'Our teaching is shaped by the finished work of Christ, union with Him, life in the Spirit, resurrection hope, and shared life in His body.',
'campuses.heading':'One family.\nLocal communities.','campuses.intro':'Epignosis Christian Family gathers in local communities that share the same Christ-centered message, discipleship culture, and mission.',
'baguio.name':'Baguio City','baguio.region':'Benguet','baguio.address':'67 Marcos Highway, Baguio City','baguio.time':'Sunday, 10:00 AM','baguio.description':'The primary campus community of ECF, gathering for Sunday worship, discipleship, leadership training, and house church life.','baguio.map':'','baguio.parking':'Please contact us before your visit for help with directions, parking, or access to the gathering.','baguio.image':'/images/ecf-sign.jpg','baguio.children':'Children are welcome in our gatherings. Please contact us about current arrangements for children before your visit.',
'san-nicolas.name':'San Nicolas','san-nicolas.region':'Ilocos Norte','san-nicolas.address':'','san-nicolas.time':'','san-nicolas.description':'A local community expression of ECF committed to Christ-centered teaching and shared life.','san-nicolas.map':'','san-nicolas.parking':'Contact us for the current gathering place and time.','san-nicolas.image':'',
'candon.name':'Candon','candon.region':'Ilocos Sur','candon.address':'','candon.time':'','candon.description':'A local community expression of ECF where believers gather for discipleship, worship, and mission.','candon.map':'','candon.parking':'Contact us for the current gathering place and time.','candon.image':'',
'visit.heading':'Come as you are.\nTake your time.','visit.intro':'We would be glad to welcome you to Epignosis Christian Family. You can come, listen, ask questions, and take your next step in Christ.','visit.expect':'Every Sunday we gather to worship, hear Christ-centered teaching from Scripture, pray together, and strengthen one another as the family of God. There is time to connect. Some Sundays also include testimonies, a shared meal, or other expressions of family life.',
'house.heading':'Faith grows in shared life.','house.intro':'House churches are smaller gatherings where we pray, discuss Scripture, care for one another, and learn to participate in service and mission.','house.body':'Sunday gatherings help us hear the Word together. House churches help us live the Word together.\n\nDiscipleship is not a ladder for proving maturity. We see growth as a spiral around Christ. Belonging, wisdom, service, and mission remain part of our life together. We do not graduate from Christ, we grow by returning.',
'college.heading':'Learn to serve\nwith clarity and care.','college.intro':'Epignosis Leadership College equips believers for faithful service in the body of Christ.','college.body':'The training is shaped by Scripture, Christ-centered theology, spiritual formation, and practical ministry wisdom.\n\nIt is for believers who desire to grow in Scripture, leadership character, teaching, discipleship, and practical service. The aim is faithful service shaped by Christ.','college.locations':'Shilan, Benguet and Baguio City','college.details':'Contact the college for current schedules, program information, and enrollment details.',
'give.heading':'Generosity that serves\nthe family and the mission.','give.intro':'Giving is not a transaction with God. It is one way believers participate in the mission of Christ through His body.','give.body':'Through faithful generosity, we support discipleship, leadership training, campus communities, outreach, and the ongoing work of revealing Christ and equipping His family.','give.paymentUrl':'','give.bankName':'','give.accountName':'','give.accountNumber':'','give.instructions':'Please contact our finance team for current giving options and bank transfer details.',
'contact.heading':'We would be glad\nto hear from you.','contact.intro':'Whether you want to visit, request prayer, or ask a question, there is a place to begin. You do not have to figure out the next step alone.','contact.phone1':'0906 329 4940','contact.phone2':'0966 387 9553','contact.email':'','contact.facebook':'','contact.youtube':'','contact.privacyEmail':'',
'prayer.heading':'Let us pray with you.','prayer.intro':'We count it a privilege to pray with you. Share as much or as little as you are comfortable sharing. If you would like someone to follow up, please let us know.',
'privacy.contact':'To ask about information you have shared, request a correction, or ask for its removal, contact ECF using the phone numbers on this site.','privacy.retention':'Contact messages are kept while follow-up is active. The site owner can delete a message when it is no longer needed. Please contact us if you would like your information removed.',
};
export const campusIds=['baguio','san-nicolas','candon'];
export const categories=['Christ and the Gospel','Salvation','Union With Christ','Finished Work of Christ','Reading Scripture Through Christ','Life in the Spirit','Resurrection Hope','Church and Shared Life','Discipleship and Formation','House Church','Grace-Gifts and Service','Mission and Witness','Leadership and Service','Bible Study','Questions New Believers Ask','WPMN and ECF Life'];
export type RecordItem={id:string;kind:'sermon'|'article'|'event'|'series'|'faq';title:string;slug:string;status:'draft'|'published';data:Record<string,string>;updatedAt?:string;version?:number};
export const beliefs=[
 ['Christ at the center','The Scriptures find their center and fulfillment in Christ. We read the whole Bible in light of God’s revelation in His Son, especially His death, resurrection, and the new life given to believers in Him.','Luke 24:27; John 5:39; Hebrews 1:1–3','/articles/what-does-christ-centered-mean'],
 ['The finished work of Christ','Salvation is God’s work in Christ, received by faith. Believers do not earn acceptance by religious effort. Christ’s once-for-all offering is the foundation of our confidence before God.','Ephesians 2:8–10; Hebrews 10:10–14','/articles/what-is-the-finished-work-of-christ'],
 ['Union with Christ','The believer’s life begins in Christ. We share in His life as members of His body. Discipleship and service flow from this belonging, through the work of the Spirit.','Romans 6:4–5; Colossians 3:1–4; 1 Corinthians 12:12–13','/articles/what-is-union-with-christ'],
 ['Life in the Spirit','The Spirit enables believers to live in the life they have received in Christ. He produces fruit, strengthens the family, and supplies grace for serving one another.','Galatians 5:22–25; Romans 8:9–11; 1 Peter 4:10–11','/media?category=Life%20in%20the%20Spirit'],
 ['Resurrection hope','Our hope is anchored in the risen Christ. We look forward to bodily resurrection and live with confidence and endurance as we serve Him now.','1 Corinthians 15:20–23, 50–58; Romans 8:23–25','/media?category=Resurrection%20Hope'],
 ['Shared life and mission','We are members of one body, learning to care, serve, forgive, and grow together. Mission includes the ordinary witness of Christ’s people in homes, schools, workplaces, neighborhoods, and nations.','Ephesians 4:15–16; Colossians 3:12–17; 2 Corinthians 5:18–20','/house-churches']
];
export const values=[['Love as our motivation','We serve because of the love we have received in Christ. His love shapes our care for one another.'],['Christ at the center','He is the center of Scripture, salvation, discipleship, worship, and mission.'],['The finished work of Christ','We stand on what Christ has accomplished through His death and resurrection.'],['The hope of resurrection','Because Christ lives, we live with confidence, endurance, and expectation.'],['Scripture interpreted through Christ','We read the whole Bible in light of Christ and its fulfillment in Him.'],['Shared life in the body','We are members of one body, learning to care, serve, forgive, and grow together.'],['Discipleship through participation','We grow as we hear, practice, serve, ask questions, and walk with others.'],['Service as grace in action','We serve from belonging, through the gifts and responsibilities God gives His people.'],['Mission as everyday life','Our witness extends into homes, schools, workplaces, neighborhoods, and nations.'],['Excellence with humility','We serve with care, order, and faithfulness.']];
export const faqs=[
 ['General','What is World Prayer and Missions Network?','WPMN is a Christ-centered mission network committed to revealing Christ, equipping His family, and discipling the nations through prayer, teaching, discipleship, leadership training, and local communities.'],
 ['General','Is Epignosis Christian Family a church?','Yes. ECF functions as a Christ-centered church family gathered around the gospel, Scripture, prayer, discipleship, and shared life in the body of Christ. It is a visible community expression of WPMN.'],
 ['General','What does “campus community” mean?','A campus community is a local expression of the same spiritual family. Each gathers in its own location and shares the same Christ-centered message, mission, and discipleship culture.'],
 ['Visiting','Can I visit even if I am not a member?','Yes. You are welcome to attend, listen, ask questions, and take time to understand the community.'],
 ['Visiting','What should I wear?','Come respectfully and comfortably. You do not need to dress in a way that feels artificial to you.'],
 ['Visiting','Do I need to bring anything?','A Bible, notebook, and pen are helpful. If you do not have those, you are still welcome.'],
 ['Beliefs','Do you teach salvation by grace?','Yes. Salvation is God’s work in Christ, received by faith. Believers do not earn salvation by religious effort. Christian life flows from union with Christ and the work of the Spirit.'],
 ['Beliefs','How do you read the Old Testament?','We honor the Old Testament as Scripture and read it through Christ. The law, shadows, promises, priesthood, sacrifices, and prophetic hope find their fulfillment in Him.'],
 ['Community','What is a house church?','A house church is a smaller gathering where believers share life, pray, discuss Scripture, care for one another, and grow in participation. It complements our Sunday gathering.'],
 ['Community','How do I join a house church?','Use the house church interest form, speak with a Connect Team member, or ask a pastor after the Sunday gathering. We can help you find a group that fits your location and availability.'],
 ['Community','What is the discipleship pathway?','The pathway helps people grow from welcome into shared life, Christ-centered understanding, service, and mission. It includes welcome conversations, Bible study, devotional rhythms, house church life, and guided participation.'],
 ['Community','Do I need to be mature before serving?','You can learn to serve as you grow. Service should be healthy and guided. We help people serve from belonging in Christ, with appropriate care and preparation for each responsibility.'],
 ['Giving','What does giving support?','Giving supports discipleship, leadership training, campus communities, outreach, ministry operations, and the continuing work of revealing Christ and equipping His family.'],
 ['Giving','Can I give by bank transfer?','Please contact our finance team for confirmed bank transfer details and receipt questions.'],
 ['College','Who is Leadership College for?','It is for believers who desire to grow in Scripture, Christ-centered theology, leadership character, and practical service in the body of Christ.'],
 ['College','Where does the college operate?','Training locations include Shilan, Benguet and Baguio City. Contact the college for current schedules and enrollment information.']
];
export const articleIdeas=[
'What Does Christ-Centered Mean?','Why the Gospel Is About What Christ Has Done','What Is the Finished Work of Christ?','Why Salvation Is Not Human Performance','What Does It Mean to Be In Christ?',
'What Is Union With Christ?','Why Christian Identity Begins in Christ','How Union With Christ Changes Discipleship','Why Believers Serve From Belonging, Not For Belonging','Why Grace Does Not Make People Passive',
'How Should Christians Read the Old Testament?','Why Scripture Must Be Read Through Christ','What Jesus Meant When He Said the Scriptures Testify About Him','How the Law Points to Christ','Why Context Matters in Bible Study',
'What Is Discipleship?','Why Discipleship Happens in Community','What Is a House Church?','How New Believers Can Start Reading the Bible','How to Grow Without Falling Back Into Performance',
'What to Expect When Visiting ECF Baguio','Why Shared Life Matters in the Body of Christ','Why We Gather on Sundays','Why We Practice House Church Life','How Service Works in a Christ-Centered Church',
'What Is Epignosis Leadership College?','Why Leadership Must Begin With Christ','What Is Mission as Everyday Life?','What Is the Difference Between Mission and Missions?','How WPMN Serves Churches, Families, and Nations'];
export const slugify=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const articleBodies:Record<string,{excerpt:string;body:string;category:string}>={
'what-does-christ-centered-mean':{category:'Christ and the Gospel',excerpt:'Why we read Scripture and understand our life together in the light of Christ.',body:'Christ is the center and fulfillment of Scripture. When Jesus spoke with His disciples after His resurrection, He explained the Scriptures in relation to Himself (Luke 24:27). In John 5:39, He told His hearers that the Scriptures testify about Him.\n\nThis shapes the questions we bring to the Bible. We ask what a passage says in its own setting and how it belongs within God’s revelation fulfilled in Christ. We pay attention to who is speaking, who is being addressed, and the place of that passage in the whole story.\n\nThe gospel announces what God has accomplished in His Son. Through His death and resurrection, Christ has dealt with sin and brought believers into new life. We receive this salvation by grace through faith (Ephesians 2:8–10).\n\nOur discipleship, worship, and service grow from this life in Him. We keep returning to Christ as we learn to love, understand Scripture, and serve together.'},
'what-is-the-finished-work-of-christ':{category:'Finished Work of Christ',excerpt:'Our confidence before God rests on what His Son has accomplished.',body:'The finished work of Christ refers to what He accomplished through His death and resurrection for our salvation. Hebrews 10:10–14 directs our attention to His once-for-all offering. His saving work is sufficient; we do not add to His sacrifice.\n\nSalvation is received by faith. Ephesians 2:8–10 places good works within the life God has given us in Christ. We are created in Him for good works, while grace remains the source of our salvation.\n\nThis gives believers a foundation for growth. We can receive correction, turn from sin, and learn to serve with confidence in Christ. His finished work does not make care, holiness, or service unimportant. It gives our life with God its proper beginning.\n\nAs we gather, pray, and read Scripture, we return to what Christ has done. Our hope rests in the risen Lord who has brought us into life with Him.'},
'what-is-union-with-christ':{category:'Union With Christ',excerpt:'Christian identity and growth begin with the life believers have received in Him.',body:'Union with Christ means that believers share in the life of the risen Lord. Paul speaks of our life in relation to Christ’s death and resurrection (Romans 6:4–5; Colossians 3:1–4). Being in Christ shapes how we understand salvation and how we live.\n\nThis life is also shared with His people. First Corinthians 12:12–13 describes believers as members of one body. We belong to Christ and receive one another as members of His family.\n\nDiscipleship grows from this belonging. Through Scripture, prayer, shared life, and the work of the Spirit, we learn to live consistently with the life we have received. We need instruction, patience, correction, and help from one another.\n\nService belongs within that growth. Each believer can learn to steward what God supplies for the good of others (1 Peter 4:10–11). Our responsibilities may differ, but Christ remains the source of our life together.'},
'what-is-the-difference-between-mission-and-missions':{category:'Mission and Witness',excerpt:'Understanding everyday witness and organized outreach within the same mission.',body:'Mission refers to our participation in God’s reconciling work through Christ. Second Corinthians 5:18–20 connects reconciliation to Christ and the message entrusted to His people. This shapes our witness in ordinary life.\n\nOur homes, schools, workplaces, and neighborhoods are places where we speak of Christ and live in love toward others. Hospitality, prayer, care, and honest conversation belong within that shared life. Our practical care does not replace the message of reconciliation in Christ.\n\nMissions refers to organized, sent, cross-cultural, or structured expressions of this participation. A planned outreach, a training partnership, or support for a pioneering church can be an expression of missions.\n\nThese organized efforts flow from the mission we share. They help the church serve beyond its immediate community, while everyday witness continues wherever Christ’s people live.'}
};
export const defaultRecords:RecordItem[]=[
 ...articleIdeas.map((title,i)=>{const slug=slugify(title), a=articleBodies[slug];return {id:'article-'+i,kind:'article' as const,title,slug,status:a?'published' as const:'draft' as const,data:{category:a?.category||categories[Math.floor(i/5)]||'Discipleship and Formation',author:'WPMN & ECF',date:'',excerpt:a?.excerpt||'',body:a?.body||'',image:'',imageAlt:'',seoTitle:title,metaDescription:a?.excerpt||'',relatedSermons:''}}}),
 {id:'series-salvation',kind:'series',title:'Salvation in Christ',slug:'salvation-in-christ',status:'published',data:{excerpt:'The finished work of Christ, union with Him, life in the Spirit, and participation in God’s mission.',body:'This series explores salvation as God’s finished act in Christ, union with Christ, life in the Spirit, and participation in God’s mission. Salvation is received by faith, lived by the Spirit, and expressed in love, service, and mission.',purpose:'To ground believers in the salvation they have received in Christ and help them live from that understanding.',nextTeaching:'/articles/what-is-the-finished-work-of-christ',notesUrl:'',relatedArticles:'what-is-the-finished-work-of-christ,what-is-union-with-christ'}},
 {id:'sermon-old-record',kind:'sermon',title:'When the Old Record Lost Its Voice',slug:'when-the-old-record-lost-its-voice',status:'draft',data:{category:'Finished Work of Christ',scripture:'Colossians 2:12–15',series:'salvation-in-christ',speaker:'',date:'',campus:'Baguio',excerpt:'In this teaching, we see that the cross did more than forgive isolated sins. In Christ, the old record lost its condemning voice, and God raised us into new life with Him.',videoUrl:'',audioUrl:'',transcript:'',questions:'',notesUrl:'',tags:'',relatedArticles:'what-is-the-finished-work-of-christ'}},
 ...faqs.map(([category,title,answer],i)=>({id:'faq-'+i,kind:'faq' as const,title,slug:'faq-'+i,status:'published' as const,data:{category,body:answer}}))
];
export const routing:Record<string,{label:string;team:string;hours:number;tags:string[]}>={
visitor:{label:'I am visiting for the first time',team:'Connect Team',hours:24,tags:['New Visitor','Needs Follow-Up']},
prayer:{label:'I want to request prayer',team:'Prayer Team',hours:24,tags:['Prayer Request']},
house:{label:'I want to join a house church',team:'House Church Coordinator',hours:48,tags:['House Church Interest','Needs Placement']},
discipleship:{label:'I want to know more about discipleship',team:'Discipleship Coordinator',hours:48,tags:['Discipleship Interest','Needs Follow-Up']},
college:{label:'I want to inquire about Leadership College',team:'ELC Admin',hours:72,tags:['Leadership College Inquiry','Needs Follow-Up']},
partnership:{label:'I want to explore WPMN partnership',team:'WPMN Leadership',hours:72,tags:['WPMN Partnership','Needs Follow-Up']},
giving:{label:'I have a giving question',team:'Finance / Admin',hours:72,tags:['Giving Question','Needs Follow-Up']},
general:{label:'I have a general question',team:'Admin / Connect Team',hours:72,tags:['Needs Follow-Up']}
};
values.forEach(([title,body],i)=>{defaults['value.'+i+'.title']=title;defaults['value.'+i+'.body']=body;});
beliefs.forEach(([title,body,scripture],i)=>{defaults['belief.'+i+'.title']=title;defaults['belief.'+i+'.body']=body;defaults['belief.'+i+'.scripture']=scripture;});
