import {env} from 'cloudflare:workers';
import {defaults,defaultRecords,type RecordItem} from './defaults';
export function db(){const binding=(env as unknown as {DB?:D1Database}).DB;if(!binding)throw new Error('Database unavailable');return binding;}
export function bucket(){const binding=(env as unknown as {BUCKET?:R2Bucket}).BUCKET;if(!binding)throw new Error('Uploads unavailable');return binding;}
export function runtime(key:string){return String((env as unknown as Record<string,unknown>)[key]||'');}
export async function getContent(strict=false){try{const rows=await db().prepare('SELECT key, value, version FROM settings').all<{key:string;value:string;version:number}>();const settings={...defaults};const versions:Record<string,number>={};for(const row of rows.results){if(row.key in defaults){settings[row.key]=row.value;versions[row.key]=row.version;}}const result=await db().prepare('SELECT * FROM records ORDER BY updated_at DESC').all<Record<string,unknown>>();const map=new Map(defaultRecords.map(r=>[r.id,{...r,version:0}]));for(const r of result.results)map.set(String(r.id),{id:String(r.id),kind:r.kind as RecordItem['kind'],title:String(r.title),slug:String(r.slug),status:r.status as RecordItem['status'],data:JSON.parse(String(r.data)),updatedAt:String(r.updated_at),version:Number(r.version)});return {settings,versions,records:Array.from(map.values()),available:true};}catch(e){console.error('Content loading failed',e);if(strict)throw e;return {settings:{...defaults},versions:{},records:defaultRecords,available:false};}}
export async function getPublicContent(){const c=await getContent(true);return {...c,records:c.records.filter(r=>r.status==='published')};}
export function safeUrl(value:string){if(value.startsWith('/')&&!value.startsWith('//')&&!value.includes('\\'))return value;try{const u=new URL(value);if(u.protocol==='https:'&&!u.username&&!u.password)return u.href;}catch{}return '';}
export function youtubeId(value:string){try{const u=new URL(value);const id=u.hostname==='youtu.be'?u.pathname.slice(1):['www.youtube.com','youtube.com','m.youtube.com'].includes(u.hostname)?u.searchParams.get('v')||u.pathname.split('/').pop():null;return id&&/^[a-zA-Z0-9_-]{11}$/.test(id)?id:null;}catch{return null;}}
