import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,index,uniqueIndex,check} from 'drizzle-orm/sqlite-core';
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull(),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()});
export const records=sqliteTable('records',{id:text('id').primaryKey(),kind:text('kind').notNull(),title:text('title').notNull(),slug:text('slug').notNull(),status:text('status').notNull().default('draft'),data:text('data').notNull(),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[index('idx_records_kind_status').on(t.kind,t.status),uniqueIndex('idx_records_kind_slug').on(t.kind,t.slug)]);
export const editors=sqliteTable('editors',{userId:text('user_id').primaryKey(),email:text('email').notNull(),role:text('role').notNull(),createdAt:text('created_at').notNull()});
export const claims=sqliteTable('claims',{id:text('id').primaryKey(),userId:text('user_id').notNull()});
export const submissions=sqliteTable('submissions',{id:text('id').primaryKey(),category:text('category').notNull(),payload:text('payload').notNull(),confidential:integer('confidential').notNull().default(0),team:text('team').notNull(),status:text('status').notNull().default('New'),assignee:text('assignee').notNull().default(''),followUp:text('follow_up').notNull().default(''),responseDueAt:text('response_due_at').notNull().default(''),notes:text('notes').notNull().default(''),tags:text('tags').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_submissions_status_date').on(t.status,t.createdAt)]);
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull().default(1),expiresAt:integer('expires_at').notNull()});
export const assets=sqliteTable('assets',{id:text('id').primaryKey(),name:text('name').notNull(),type:text('type').notNull(),owner:text('owner').notNull(),createdAt:text('created_at').notNull()});

export const writeGuards=sqliteTable('write_guards',{id:text('id').primaryKey(),valid:integer('valid').notNull()},t=>[check('write_guard_valid',sql`${t.valid} = 1`)]);
export const auditEvents=sqliteTable('audit_events',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),createdAt:text('created_at').notNull()});
