import {z} from 'zod';
import {db,runtime} from '@/lib/store';import {sameOrigin,reply,rateLimit,readJson,routeError} from '@/lib/security';import {routing} from '@/lib/defaults';
export const dynamic='force-dynamic';
const fields=['firstName','lastName','phone','email','campus','message','thisSunday','company','children','heardFrom','location','availability','attending','newToEcf','newToFaith','interest','church','trainingLocation','serving','contactMethod','organization','role','partnershipType','givingHelp','subject','visitDate'];
const contactInput=z.object({id:z.string().uuid(),reason:z.string().refine(x=>Object.hasOwn(routing,x)),consent:z.literal(true),data:z.record(z.string().max(5000)).refine(x=>Object.keys(x).every(k=>fields.includes(k)||k==='website')),followUp:z.boolean().optional(),confidential:z.boolean().optional(),startedAt:z.number().finite().optional()}).strict();
export async function POST(req:Request){if(!sameOrigin(req))return reply({error:'Please use the contact form on this website.'},403);try{const parsed=contactInput.safeParse(await readJson(req,20000));if(!parsed.success)return reply({error:'Please check the submitted fields and consent.'},400);const body=parsed.data;if(body.data?.website)return reply({ok:true});if(typeof body.id!=='string'||! /^[a-f0-9-]{36}$/.test(body.id)||!Object.hasOwn(routing,body.reason)||body.consent!==true)return reply({error:'Please complete the required fields and privacy consent.'},400);const data:Record<string,string>={};for(const key of fields){if(body.data?.[key]!==undefined){if(typeof body.data[key]!=='string')return reply({error:'Please check your message.'},400);data[key]=body.data[key].trim();if(data[key].length>(key==='message'?5000:500))return reply({error:'Please shorten the '+key+' field.'},400);}}
if((!data.firstName&&body.reason!=='prayer')||(!data.message&&body.reason!=='visitor'))return reply({error:'Please add your name and message.'},400);if(data.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))return reply({error:'Please enter a valid email address.'},400);if((body.reason!=='prayer'||body.followUp===true)&&!data.email&&!data.phone)return reply({error:'Please include a phone number or email address for follow-up.'},400);if(data.contactMethod==='Email'&&!data.email||data.contactMethod==='Phone'&&!data.phone)return reply({error:'Please add details for your preferred contact method.'},400);
const existing=await db().prepare('SELECT id FROM submissions WHERE id = ?').bind(body.id).first();if(existing)return reply({ok:true});if(!await rateLimit(req,'contact'))return reply({error:'Several messages have been sent recently. Please try again later, or call us.'},429);
const route=routing[body.reason];const confidential=body.reason==='prayer'||body.reason==='discipleship'&&data.interest==='Pastoral care';const team=confidential?'Pastoral Team':body.reason==='giving'&&data.givingHelp==='Partnership'?'WPMN Leadership':route.team;const now=new Date().toISOString();const due=new Date(Date.now()+route.hours*3600000).toISOString();const tags=[...route.tags,...(data.campus?['Campus: '+data.campus]:[]),...(confidential?['Pastoral Care']:[]),...(data.children==='Yes'?['Children Attending']:[]),...(data.thisSunday==='Yes'?['Sunday Visit Planned']:[])];const payload=JSON.stringify({...data,followUp:body.reason==='prayer'?body.followUp===true:true,privacyConsent:true,consentedAt:now,consentVersion:'contact-2026-09',consentPurpose:'Respond to this request only'});await db().prepare('INSERT INTO submissions (id,category,payload,confidential,team,status,assignee,follow_up,response_due_at,notes,tags,created_at,updated_at) VALUES (?,?,?,?,?,\'New\',\'\',\'\',?,\'\',?,?,?) ON CONFLICT(id) DO NOTHING').bind(body.id,body.reason,payload,confidential?1:0,team,due,JSON.stringify(tags),now,now).run();return reply({ok:true});}catch(e){return routeError(e);}}
