import {editorInput} from '@/lib/editor-input';
import {permits,sensitiveSetting} from '@/lib/permissions';
import {settingsGuard,recordGuard,submissionGuard,clearGuard,saveSetting,saveRecord,auditWrite} from '@/lib/write-sql';
import {isBrandColor,brandImage} from '@/lib/brand';
import {db,getContent,runtime,safeUrl,youtubeId} from '@/lib/store';
import {defaults,type RecordItem} from '@/lib/defaults';import {getChatGPTUser} from '@/app/chatgpt-auth';import {protectedRoute,reply,sameOrigin,readJson,hash,rateLimit,HttpError,routeError} from '@/lib/security';
export const dynamic='force-dynamic';
export const GET=protectedRoute('content',async(_req,user)=>{const content=await getContent(true);const messages=user.role==='pastoral-owner'?await db().prepare('SELECT * FROM submissions ORDER BY created_at DESC LIMIT 500').all<Record<string,unknown>>():{results:[]};return reply({...content,messages:messages.results.map(m=>({...m,payload:JSON.parse(String(m.payload)),tags:JSON.parse(String(m.tags))})),user:{name:user.displayName,role:user.role}});});
const kinds=['sermon','article','event','series','faq'];
export async function POST(req:Request){if(!sameOrigin(req))return reply({error:'Please use the editor on this website.'},403);try{const parsed=editorInput.safeParse(await readJson(req,250000));if(!parsed.success)return reply({error:'Please check the submitted fields.'},400);const body=parsed.data;if(body.action==='claim'){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in with ChatGPT first.'},401);if(!await rateLimit(req,'claim',8))return reply({error:'Please wait before trying again.'},429);if(typeof body.token!=='string'||body.token.length>200||!runtime('EDITOR_SETUP_HASH')||await hash(body.token)!==runtime('EDITOR_SETUP_HASH'))return reply({error:'Use the private editor setup link provided with your website.'},403);const existing=await db().prepare('SELECT user_id FROM claims WHERE id = ?').bind('owner').first<{user_id:string}>();if(existing)return existing.user_id===user.userId?reply({ok:true}):reply({error:'This website already has an owner.'},403);try{await db().batch([db().prepare('INSERT INTO claims (id,user_id) VALUES (?,?)').bind('owner',user.userId),db().prepare('INSERT INTO editors (user_id,email,role,created_at) VALUES (?,?,?,?)').bind(user.userId,user.email,'pastoral-owner',new Date().toISOString())]);}catch(e){const winner=await db().prepare('SELECT user_id FROM claims WHERE id = ?').bind('owner').first<{user_id:string}>();if(winner)return winner.user_id===user.userId?reply({ok:true}):reply({error:'This website already has an owner.'},403);throw e;}return reply({ok:true});}
return await protectedRoute('content',async(_req,user)=>{const now=new Date().toISOString();
if(body.action==='settings'){const changes=body.changes;if(changes.some(c=>sensitiveSetting(c.key))&&!permits(user.role,'giving'))return reply({error:'Only the pastoral owner may change giving destinations.'},403);if(!Array.isArray(changes)||changes.length>200)return reply({error:'Please save a smaller set of changes.'},400);for(const c of changes){if(!Object.hasOwn(defaults,c.key)||typeof c.value!=='string'||c.value.length>15000)return reply({error:'One field is not valid.'},400);if(c.value&&(/Image$|\.image$|\.map$|\.paymentUrl$|\.facebook$|\.youtube$/.test(c.key))&&!safeUrl(c.value))return reply({error:'Please use an HTTPS link or an uploaded image.'},400);if(c.value&&/Email$|\.email$/.test(c.key)&&! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.value))return reply({error:'Please check the email address.'},400);if(['brand.midnightViolet','brand.faithTeal'].includes(c.key)&&!isBrandColor(c.value))return reply({error:'Use a six-digit hex color with enough contrast for white text (at least 4.5:1).'},400);if(c.key==='brand.siteName'&&(!c.value.trim()||c.value.length>60))return reply({error:'Use a website name between 1 and 60 characters.'},400);if(c.key.startsWith('brand.')&&c.key.endsWith('Image')&&c.value){if(!brandImage(c.value))return reply({error:'Upload your logo in Photos & files and paste its uploaded link.'},400);const asset=c.value.startsWith('/images/ecf-')?{type:'image/png'}:await db().prepare('SELECT type FROM assets WHERE id = ?').bind(c.value.split('/').pop()).first<{type:string}>();if(!asset||!['image/png','image/jpeg','image/webp'].includes(asset.type))return reply({error:'Choose an uploaded PNG, JPG, or WebP image for your brand.'},400);}if(c.key.startsWith('seo.')&&c.key.endsWith('Verification')&&c.value&&!/^[A-Za-z0-9_-]{1,200}$/.test(c.value))return reply({error:'Paste only the verification code, not the whole HTML tag.'},400);if(c.key==='seo.homeTitle'&&c.value.length>160)return reply({error:'Keep the homepage search title below 160 characters.'},400);if(c.key==='seo.homeDescription'&&c.value.length>400)return reply({error:'Keep the homepage search description below 400 characters.'},400);}
if(changes.length){const guard=crypto.randomUUID();try{await db().batch([
 db().prepare(settingsGuard).bind(guard,JSON.stringify(changes)),
 ...changes.map(c=>db().prepare(saveSetting).bind(c.key,c.value,now)),
 ...changes.filter(c=>sensitiveSetting(c.key)).map(c=>db().prepare(auditWrite).bind(crypto.randomUUID(),user.userId,'giving-setting',c.key,now)),
 db().prepare(clearGuard).bind(guard)
]);}catch(e){if(String(e).includes('CHECK constraint failed'))throw new HttpError(409,'This text changed in another editing session. Reload before saving.');throw e;}}return reply({ok:true});}
if(body.action==='record'){const r=body.record as RecordItem;if(!r||typeof r.id!=='string'||r.id.length>100||!kinds.includes(r.kind)||!['draft','published'].includes(r.status)||typeof r.title!=='string'||!r.title.trim()||r.title.length>250||! /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(r.slug))return reply({error:'Add a title and a web address using lowercase words separated by hyphens.'},400);const data:Record<string,string>={};if(!r.data||typeof r.data!=='object')return reply({error:'Content is missing.'},400);for(const [key,value] of Object.entries(r.data)){if(typeof value!=='string'||value.length>120000)return reply({error:'Content is too long.'},400);data[key]=value.trim();if(value&&/Url$|^image$|^nextTeaching$/.test(key)&&!safeUrl(value))return reply({error:'Links must start with https:// or a site path.'},400);}if(data.videoUrl&&!youtubeId(data.videoUrl))return reply({error:'Use a valid YouTube watch, share, or Shorts link.'},400);if(r.status==='published'){if(['article','faq','series'].includes(r.kind)&&!data.body)return reply({error:'Add the written content before publishing.'},400);if(r.kind==='sermon'&&!data.videoUrl&&!data.audioUrl&&!data.transcript)return reply({error:'Add a video, audio recording, or transcript before publishing this sermon.'},400);if(r.kind==='event'&&(!data.date||!data.location))return reply({error:'Add the event date and location before publishing.'},400);if(data.image&&!data.imageAlt)return reply({error:'Add a short description of the image for accessibility.'},400);}
const content=await getContent(true);if(content.records.some(x=>x.id!==r.id&&x.kind===r.kind&&x.slug===r.slug))return reply({error:'Another item uses that web address. Choose a different one.'},409);const current=content.records.find(x=>x.id===r.id);if((current?.version||0)!==(r.version||0))return reply({error:'This item changed in another session. Reload before saving.'},409);const guard=crypto.randomUUID();try{await db().batch([
 db().prepare(recordGuard).bind(guard,r.id,r.version||0),
 db().prepare(saveRecord).bind(r.id,r.kind,r.title.trim(),r.slug,r.status,JSON.stringify(data),now),
 db().prepare(clearGuard).bind(guard)
]);}catch(e){if(String(e).includes('CHECK constraint failed'))throw new HttpError(409,'This item changed in another session. Reload before saving.');if(String(e).includes('UNIQUE constraint failed'))throw new HttpError(409,'Another item uses that web address. Choose a different one.');throw e;}return reply({ok:true});}
if(body.action==='message'){if(user.role!=='pastoral-owner')return reply({error:'Pastoral owner access is required.'},403);if(typeof body.id!=='string'||!['New','In progress','Follow-up scheduled','Complete'].includes(body.status))return reply({error:'Please choose a valid status.'},400);for(const key of ['assignee','followUp','notes'] as const)if(typeof body[key]!=='string'||body[key].length>(key==='notes'?5000:300))return reply({error:'Please check the follow-up details.'},400);if(!Array.isArray(body.tags)||body.tags.length>30||body.tags.some((t:unknown)=>typeof t!=='string'||t.length>100))return reply({error:'Please use a short list of pathway tags.'},400);const guard=crypto.randomUUID();try{await db().batch([
 db().prepare(submissionGuard).bind(guard,body.id),
 db().prepare('UPDATE submissions SET status=?,assignee=?,follow_up=?,notes=?,tags=?,updated_at=? WHERE id=?').bind(body.status,body.assignee,body.followUp,body.notes,JSON.stringify(body.tags.filter(Boolean)),now,body.id),
 db().prepare(auditWrite).bind(crypto.randomUUID(),user.userId,'update-submission',body.id,now),db().prepare(clearGuard).bind(guard)
]);}catch(e){if(String(e).includes('CHECK constraint failed'))throw new HttpError(404,'That request no longer exists.');throw e;}return reply({ok:true});}
if(body.action==='delete-message'){if(user.role!=='pastoral-owner')return reply({error:'Pastoral owner access is required.'},403);if(typeof body.id!=='string')return reply({error:'Choose a message.'},400);const guard=crypto.randomUUID();try{await db().batch([
 db().prepare(submissionGuard).bind(guard,body.id),
 db().prepare(auditWrite).bind(crypto.randomUUID(),user.userId,'delete-submission',body.id,now),
 db().prepare('DELETE FROM submissions WHERE id = ?').bind(body.id),db().prepare(clearGuard).bind(guard)
]);}catch(e){if(String(e).includes('CHECK constraint failed'))throw new HttpError(404,'That request no longer exists.');throw e;}return reply({ok:true});}return reply({error:'Unknown action.'},400);
})(req);
}catch(e){return routeError(e);}}
