import {siteOrigin,websiteData} from '@/lib/seo';
import Link from '@/components/site/site-link';
import {BookOpen,Users,Play,Heart,MessageCircle,ArrowUpRight,MapPin,Clock,Globe2} from 'lucide-react';
import {Shell,TextLink,Paragraphs,CampusCards,ArticleCards,ConnectBand} from '@/components/site/ui';
import {getPublicContent,safeUrl} from '@/lib/store';
export const dynamic='force-dynamic';
export function generateMetadata(){return {alternates:{canonical:siteOrigin()+'/'}};}
export default async function Home(){const {settings:s,records}=await getPublicContent();const paths=[{name:'Join a gathering',text:'Meet ECF Baguio and know what to expect on Sunday.',href:'/visit',icon:Users,cta:'Plan a visit'},{name:'Find a house church',text:'Explore a smaller gathering for Scripture, prayer, and care.',href:'/house-churches',icon:Heart,cta:'Find a house church'},{name:'Explore teaching',text:'Begin with a sermon, Bible study, or article about Christ.',href:'/media',icon:Play,cta:'Explore teachings'},{name:'Discover discipleship',text:'Learn about welcome conversations and growing in Christ together.',href:'/discipleship',icon:BookOpen,cta:'Explore discipleship'}];return <Shell s={s}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(websiteData(s)).replace(/</g,'\\u003c')}}/>
<section className="hero"><img className="hero-photo" src={safeUrl(s['home.heroImage'])||'/images/shared-life.jpg'} alt={s['home.heroAlt']} fetchPriority="high"/><div className="hero-shade"/><div className="wrap hero-inner"><p className="eyebrow">A CHRIST-CENTERED MISSION NETWORK</p><h1 className="preserve">{s['home.heroHeading']}</h1><p className="hero-body">{s['home.heroIntro']}</p><div className="actions"><Link className="button light" href="/visit">Visit a gathering<ArrowUpRight size={17}/></Link><Link className="button outline" href="/beliefs">Explore what we teach</Link></div><Link className="hero-prayer" href="/prayer">How can we pray with you? <ArrowUpRight size={15}/></Link></div><div className="hero-caption">SHARED LIFE IN EPIGNOSIS CHRISTIAN FAMILY</div></section>
<div className="gather-strip"><div className="wrap"><div className="strip-family"><img className="strip-mark" src="/images/ecf-brandmark.png" alt="Epignosis Christian Family brand mark" width={58} height={58}/><p>Epignosis Christian Family<span>A local expression of the WPMN family</span></p></div><span className="strip-detail"><Clock size={17}/>{s['baguio.time']}</span><span className="strip-detail"><MapPin size={17}/>Baguio City</span><TextLink href="/campuses">Our communities</TextLink></div></div>
<section className="section wrap paths-section"><div className="section-heading centered"><p className="eyebrow">A SIMPLE NEXT STEP</p><h2>{s['home.pathsHeading']}</h2><p>{s['home.pathsIntro']}</p></div><div className="path-grid">{paths.map(p=><Link className="path-card" key={p.name} href={p.href}><p.icon size={25} strokeWidth={1.35}/><h3>{p.name}</h3><p>{p.text}</p><span>{p.cta}<ArrowUpRight size={15}/></span></Link>)}</div></section>
<section className="section identity-section"><div className="wrap split"><div><p className="eyebrow">WHO WE ARE</p><h2 className="preserve">{s['home.identityHeading']}</h2><div className="body-copy"><Paragraphs text={s['home.identityBody']}/></div><TextLink href="/about">Learn about WPMN and ECF</TextLink></div><div className="identity-note"><Globe2 size={40} strokeWidth={1}/><p className="note-title">One shared mission.<br/>A family across communities.</p><div className="network-name">WORLD PRAYER & MISSIONS NETWORK</div><div className="network-locations"><span>Baguio</span><span>San Nicolas</span><span>Candon</span></div><p className="small-copy">Prayer, teaching, discipleship, leadership formation, and mission.</p></div></div></section>
<section className="section belief-section"><div className="wrap split"><div><p className="eyebrow">WHAT WE TEACH</p><h2 className="preserve">{s['home.beliefsHeading']}</h2></div><div><Paragraphs text={s['home.beliefsBody']}/><TextLink href="/beliefs" light>Read our teaching posture</TextLink></div></div><div className="wrap belief-pillars"><span>The finished work of Christ</span><span>Union with Christ</span><span>Life in the Spirit</span><span>Resurrection hope</span></div></section>
<section className="section wrap"><div className="split gather-block"><div className="gather-photo"><img src={safeUrl(s['baguio.image'])||'/images/ecf-sign.jpg'} alt="Epignosis Christian Family roadside sign" loading="lazy"/><div className="photo-label">EPIGNOSIS CHRISTIAN FAMILY · BAGUIO</div></div><div><p className="eyebrow">GATHER WITH US</p><h2>{s['home.gatherHeading']}</h2><p>{s['home.gatherBody']}</p><div className="visit-mini"><p><Clock size={20}/><span><strong>Sunday gathering</strong><br/>{s['baguio.time']}</span></p><p><MapPin size={20}/><span>{s['baguio.address']}</span></p></div><Link className="button" href="/visit">Plan your visit<ArrowUpRight size={17}/></Link></div></div></section>
<section className="section campuses-section"><div className="wrap"><div className="section-heading row"><div><p className="eyebrow">OUR LOCAL COMMUNITIES</p><h2>One family, gathering in many places.</h2></div><TextLink href="/campuses">Explore our campuses</TextLink></div><CampusCards s={s}/></div></section>
<section className="section wrap"><div className="split house-block"><div><p className="eyebrow">BELONGING BEYOND SUNDAY</p><h2 className="preserve">{s['home.houseHeading']}</h2><p>{s['home.houseBody']}</p><div className="small-path"><span>Belonging</span><span>Wisdom</span><span>Service</span><span>Mission</span></div><TextLink href="/house-churches">Find a house church</TextLink></div><div className="house-photo"><img src={safeUrl(s['home.houseImage'])||'/images/shared-life.jpg'} alt={s['home.houseAlt']} loading="lazy"/><div className="photo-label">LEARNING, CARING, AND GROWING TOGETHER</div></div></div></section>
<section className="section media-section"><div className="wrap"><div className="section-heading row"><div><p className="eyebrow">TEACHING FOR EVERYDAY LIFE</p><h2>{s['home.mediaHeading']}</h2><p>{s['home.mediaBody']}</p></div><TextLink href="/media">Explore all teachings</TextLink></div><ArticleCards records={records}/></div></section>
<section className="section wrap"><div className="college-panel"><div><p className="eyebrow">EPIGNOSIS LEADERSHIP COLLEGE</p><h2 className="preserve">{s['home.collegeHeading']}</h2><p>{s['home.collegeBody']}</p><TextLink href="/leadership-college">Explore Leadership College</TextLink></div><div className="college-side"><BookOpen size={48} strokeWidth={1}/><p>Scripture.<br/>Formation.<br/>Faithful service.</p><span>SHILAN, BENGUET · BAGUIO CITY</span></div></div></section>
<section className="giving-home wrap"><Heart size={26} strokeWidth={1.3}/><div><h2>{s['home.giveHeading']}</h2><p>{s['home.giveBody']}</p></div><Link className="button" href="/give">Give or partner<ArrowUpRight size={17}/></Link></section><ConnectBand s={s}/></Shell>}
