'use client';
import {useState,useRef} from 'react';import Link from '@/components/site/site-link';import {CheckCircle2,ArrowUpRight,LockKeyhole} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';import {Checkbox} from '@/components/ui/checkbox';import {routing} from '@/lib/defaults';
export function Choice({label,value,onChange,options,id}:{label:string;value:string;onChange:(v:string)=>void;options:string[];id:string}){return <div className="field"><label htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={id} className="select-trigger"><SelectValue placeholder="Please choose"/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>}
export function ContactForm({initialReason='general',initialCampus='',fixed=false}:{initialReason?:string;initialCampus?:string;fixed?:boolean}){const [reason,setReason]=useState(Object.hasOwn(routing,initialReason)?initialReason:'general'),[data,setData]=useState<Record<string,string>>({campus:initialCampus}),[follow,setFollow]=useState(false),[confidential,setConfidential]=useState(true),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false);const requestId=useRef(''),started=useRef(Date.now());const update=(key:string,value:string)=>setData(p=>({...p,[key]:value}));const input=(key:string,label:string,required=false,type='text')=><div className="field" key={key}><label htmlFor={reason+'-'+key}>{label}{required?' *':''}</label><input id={reason+'-'+key} name={key} type={type} required={required} maxLength={500} value={data[key]||''} onChange={e=>update(key,e.target.value)} autoComplete={key==='firstName'?'given-name':key==='lastName'?'family-name':key==='email'?'email':key==='phone'?'tel':'off'}/></div>;const choice=(key:string,label:string,options:string[])=><Choice key={key} id={reason+'-'+key} label={label} value={data[key]||''} options={options} onChange={v=>update(key,v)}/>;
async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!consent){setError('Please confirm that we may use your information to respond.');return;}if((reason!=='prayer'||follow)&&!data.email?.trim()&&!data.phone?.trim()){setError('Please include a phone number or email address so we can respond.');return;}setBusy(true);if(!requestId.current)requestId.current=crypto.randomUUID();try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId.current,reason,data,followUp:follow,confidential,consent,startedAt:started.current})});const r=await res.json() as {error?:string};if(!res.ok)throw new Error(r.error||'Your message could not be saved. Please try again.');setSuccess(true);setData({});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
if(success)return <div className="success-panel" role="status"><CheckCircle2 size={32}/><h3>Thank you for reaching out.</h3><p>{reason==='prayer'&&!follow?'Your prayer request has been received. You have not requested follow-up.':'Your message has been received. Someone from our team will review it and respond using the details you shared.'}</p>{reason==='prayer'&&<p>We will receive your prayer request with care and discretion. Your request has pastoral access only.</p>}<Link className="text-link" href="/">Return to the homepage<ArrowUpRight size={16}/></Link></div>;
return <form onSubmit={submit} className="contact-form"><h2>{reason==='prayer'?'Share a prayer request':reason==='visitor'?'Let us know you are coming':'Start a conversation'}</h2><p className="muted" style={{fontSize:'.85rem'}}>Fields marked * are required. {reason!=='prayer'?'Please give us at least one way to contact you.':'Contact details are optional unless you request follow-up.'}</p>{!fixed&&<div className="field"><label htmlFor="reason">How can we help? *</label><Select value={reason} onValueChange={v=>{setReason(v);setError('');setData({campus:data.campus||''});setConfidential(true);setFollow(false);requestId.current='';}}><SelectTrigger id="reason" className="select-trigger"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(routing).map(([v,r])=><SelectItem value={v} key={v}>{r.label}</SelectItem>)}</SelectContent></Select></div>}
<div className="field-grid">{input('firstName',reason==='prayer'?'Name or preferred name':'First name',reason!=='prayer')}{input('lastName','Last name')}</div><div className="field-grid">{input('email','Email',false,'email')}{input('phone','Phone',false,'tel')}</div>
{!['partnership','giving'].includes(reason)&&choice('campus','Which campus are you connected to or interested in?',['Baguio','San Nicolas','Candon','Not sure yet','Not connected to a campus'])}
{reason==='visitor'&&<>{input('visitDate','Preferred visit date',false,'date')}{choice('thisSunday','Are you planning to visit this Sunday?',['Yes','Another Sunday','I am still deciding'])}{choice('company','Are you coming alone or with others?',['On my own','With family','With friends'])}{choice('children','Will children be joining you?',['Yes','No','Not sure yet'])}{input('heardFrom','How did you hear about us?')}</>}
{reason==='prayer'&&<><label className="check-label"><Checkbox checked={follow} onCheckedChange={v=>setFollow(v===true)}/><span>I would like someone to follow up with me.</span></label><div className="form-notice"><LockKeyhole size={16} style={{display:'inline',marginRight:7}}/>Your request is restricted to the designated pastoral owner and is excluded from visitor exports. Please share only what is needed. You do not need to include medical details or identify other people. This form is not monitored continuously. For immediate danger, seek local emergency assistance.</div></>}
{reason==='house'&&<>{input('location','Location or barangay')}{input('availability','Preferred day or time')}{choice('attending','Are you already attending Sunday gatherings?',['Yes','Sometimes','Not yet'])}{choice('newToEcf','Are you new to ECF?',['Yes','No'])}</>}
{reason==='discipleship'&&<>{choice('newToFaith','Are you new to Christianity?',['Yes','No','I am exploring Christianity'])}{choice('newToEcf','Are you new to ECF?',['Yes','No'])}{choice('interest','What would you like help with?',['Bible reading','Prayer','Understanding the gospel','House church','Service','Leadership training','Pastoral care'])}<label className="check-label"><Checkbox checked={follow} onCheckedChange={v=>setFollow(v===true)}/><span>I would like someone to contact me.</span></label></>}
{reason==='college'&&<>{input('church','Current church or campus connection')}{input('location','Your location')}{choice('trainingLocation','Which training location are you interested in?',['Shilan, Benguet','Baguio City','I would like more information'])}{choice('serving','Are you currently serving in ministry?',['Yes','No'])}{input('interest','Area of training you are interested in')}{choice('contactMethod','Preferred contact method',['Email','Phone'])}</>}
{reason==='partnership'&&<>{input('organization','Organization or church, if any')}{input('role','Your role')}{input('location','Location')}{choice('partnershipType','What kind of partnership are you exploring?',['Teaching','Leadership training','Mission partnership','Church support','Campus ministry','Prayer partnership','Other'])}</>}
{reason==='giving'&&<>{choice('givingHelp','What would you like help with?',['Online giving','Bank transfer','Receipt','Partnership','Other'])}{choice('contactMethod','Preferred contact method',['Email','Phone'])}<p className="form-notice">Please do not include card numbers, passwords, or other financial account credentials.</p></>}
{reason==='general'&&input('subject','Subject')}
<div className="field"><label htmlFor="message">{reason==='prayer'?'Prayer request':reason==='visitor'?'What would help you feel prepared for your visit?':reason==='house'?'What are you hoping for in house church?':reason==='college'?'What is your reason for inquiring?':'Message'}{reason==='visitor'?'':' *'}</label><textarea id="message" required={reason!=='visitor'} maxLength={5000} value={data.message||''} onChange={e=>update('message',e.target.value)} rows={5}/></div>
<div aria-hidden="true" style={{position:'absolute',left:'-10000px'}}><label htmlFor="website">Leave this empty</label><input id="website" name="website" tabIndex={-1} autoComplete="off" value={data.website||''} onChange={e=>update('website',e.target.value)}/></div>
<label className="check-label"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="Consent to contact information use"/><span>I agree that WPMN and ECF may use this information to respond to my request. I have read the <Link href="/privacy" target="_blank">privacy notice</Link>. *</span></label>{error&&<p className="error-message" role="alert">{error}</p>}<button className="button wide" disabled={busy} type="submit">{busy?'Sending your message…':reason==='prayer'?'Send prayer request':'Send message'}<ArrowUpRight size={16}/></button></form>}
