import Link from '@/components/site/site-link';
import {ArrowUp,ArrowUpRight,ArrowRight,MapPin,Clock,Phone} from 'lucide-react';
import {Navigation} from './navigation';
import {brandImage} from '@/lib/brand';
import {BrandTagline} from './brand-tagline';
import type {RecordItem} from '@/lib/defaults';
export function TextLink({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <Link className={'text-link'+(light?' inverse':'')} href={href}>{children}<ArrowUpRight size={17}/></Link>}
export function Paragraphs({text}:{text:string}){return <>{text.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</>}
export function Footer({s}:{s:Record<string,string>}){return <footer className="site-footer"><div className="wrap footer-grid"><div className="footer-identity"><Link className="footer-brand" href="/">{brandImage(s['brand.logoImage'])&&<img className="footer-logo" src={brandImage(s['brand.logoImage'])} alt={s['brand.logoAlt']} width={150} height={80} loading="lazy"/>}{s['brand.siteName']}<span>{s['identity.name']}</span></Link><small>A Christ-centered mission network serving through prayer, teaching, shared life, and mission.</small></div><div><h4>Explore</h4>{[['About WPMN','/about'],['Epignosis Christian Family','/ecf'],['ECF campuses','/campuses'],['Discipleship','/discipleship'],['What we teach','/beliefs'],['Sermons & articles','/media'],['Leadership College','/leadership-college'],['Give','/give']].map(([label,url])=><Link key={url} href={url}>{label}</Link>)}</div><div><h4>Connect</h4>{[['Plan a visit','/visit'],['Request prayer','/prayer'],['Find a house church','/house-churches'],['Partnership inquiry','/contact?reason=partnership'],['Contact us','/contact']].map(([label,url])=><Link key={url} href={url}>{label}</Link>)}</div><div><h4>Gather with us</h4><img className="footer-logo footer-ecf-logo" src="/images/ecf-horizontal-white.png" alt="Epignosis Christian Family logo" width={220} height={53} loading="lazy"/><p>Epignosis Christian Family<br/>Baguio campus</p><p>{s['baguio.address']}<br/>{s['baguio.time']}</p><a href={'tel:'+s['contact.phone1'].replace(/\s/g,'')}>{s['contact.phone1']}</a><a href={'tel:'+s['contact.phone2'].replace(/\s/g,'')}>{s['contact.phone2']}</a>{s['contact.email']&&<a href={'mailto:'+s['contact.email']}>{s['contact.email']}</a>}</div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} {s['identity.name']}</span><span><Link href="/privacy">Privacy</Link><Link href="/editor">Website editor</Link></span></div><div className="wrap footer-tagline"><BrandTagline text={s['identity.tagline']}/></div><p className="footer-note wrap">Epignosis Christian Family is a visible community expression of WPMN.</p></footer>}
export function Shell({s,children}:{s:Record<string,string>;children:React.ReactNode}){return <><a className="skip-link" href="#main">Skip to content</a><Navigation name={s['brand.siteName']} fullName={s['identity.name']} logo={brandImage(s['brand.logoImage'])} logoAlt={s['brand.logoAlt']} tagline={s['identity.tagline']}/><div className="site-tagline"><BrandTagline text={s['identity.tagline']}/></div><main id="main">{children}</main><Footer s={s}/><a className="back-to-top" href="#top" aria-label="Back to top"><ArrowUp size={18}/><span>Top</span></a></>}
export function PageHero({label,title,intro,children}:{label:string;title:string;intro?:string;children?:React.ReactNode}){return <section className="page-hero"><div className="wrap"><p className="eyebrow">{label}</p><h1 className="preserve">{title}</h1>{intro&&<p className="lede">{intro}</p>}{children}</div></section>}
export function ConnectBand({s}:{s:Record<string,string>}){return <section className="connect-band"><div className="wrap connect-inner"><div><p className="eyebrow">YOU ARE WELCOME HERE</p><h2>{s['home.connectHeading']}</h2><p>{s['home.connectBody']}</p></div><div className="actions"><Link className="button light" href="/contact">Contact us<ArrowUpRight size={17}/></Link><Link className="button outline" href="/prayer">Request prayer</Link></div></div></section>}
export function CampusCards({s}:{s:Record<string,string>}){return <div className="campus-grid">{['baguio','san-nicolas','candon'].map((id,i)=><Link className={'campus-card campus-'+id} key={id} href={'/campuses/'+id}><img className="campus-photo" src={campusImage(s[id+'.image'])} alt={'Epignosis Christian Family '+s[id+'.name']+' campus gathering'} loading="lazy"/><div className="campus-card-body"><div className="campus-top"><MapPin size={22}/><span>{i===0?'PRIMARY CAMPUS':s[id+'.region'].toUpperCase()}</span></div><div><h3>{s[id+'.name']}</h3><p>{s[id+'.description']}</p></div><div className="campus-bottom"><span>{i===0?s[id+'.time']:'Explore this community'}</span><ArrowUpRight size={22}/></div></div></Link>)}</div>}
function campusImage(value:string){return value&&value.startsWith('/')?value:'/images/ecf-sign.jpg'}
export function ArticleCards({records,limit=3}:{records:RecordItem[];limit?:number}){return <div className="article-grid">{records.filter(r=>r.kind==='article').slice(0,limit).map((r,i)=><Link className="article-card" href={'/articles/'+r.slug} key={r.id}><div className={'article-art art-'+i%3}><span>{r.data.category}</span><p>{r.title}</p><ArrowUpRight size={25}/></div><div className="article-info"><p>{r.data.excerpt}</p><span>Read the article <ArrowRight size={15}/></span></div></Link>)}</div>}
export function ContactDetails({s}:{s:Record<string,string>}){return <div className="contact-details"><div><MapPin/><p><strong>ECF Baguio</strong><br/>{s['baguio.address']}</p></div><div><Clock/><p><strong>Sunday gathering</strong><br/>{s['baguio.time']}</p></div><div><Phone/><p><a href={'tel:'+s['contact.phone1'].replace(/\s/g,'')}>{s['contact.phone1']}</a><br/><a href={'tel:'+s['contact.phone2'].replace(/\s/g,'')}>{s['contact.phone2']}</a></p></div></div>}
